test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: meme_search_test

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: meme_search_development

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: meme_search_production
  timeout: 5000
  statement_limit: 200
